apiVersion: v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: finance-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-service
  template:
    metadata:
      labels:
        app: redis-service
    spec:
      containers:
        - name: redis
          image: redis:7.4.2
          ports:
            - containerPort: 6379
          resources:
            limits:
              cpu: 100m
              memory: 40Mi
            requests:
              cpu: 50m
              memory: 20Mi
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: finance-dev
spec:
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      nodePort: 31379
  selector:
    app: redis-service
  type: NodePort
